<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NIRANJAN" name="com.testng.Priority" tests="13" failures="1" timestamp="08 Aug 2019 05:13:19 GMT" time="289.388" errors="0">
  <testcase name="getUrl" time="7.697" classname="com.testng.Priority"/>
  <testcase name="LinkText" time="16.224" classname="com.testng.Priority"/>
  <testcase name="getTitle" time="9.257" classname="com.testng.Priority"/>
  <testcase name="fbCheckListBox" time="30.083" classname="com.testng.Priority"/>
  <testcase name="fbCheckListBox1" time="37.690" classname="com.testng.Priority"/>
  <testcase name="PrintMonthList" time="18.371" classname="com.testng.Priority"/>
  <testcase name="PrintDaysList" time="18.127" classname="com.testng.Priority"/>
  <testcase name="HandleBootstrapDropDown" time="26.556" classname="com.testng.Priority"/>
  <testcase name="selectMonth" time="17.003" classname="com.testng.Priority"/>
  <testcase name="PrintyearList" time="27.781" classname="com.testng.Priority"/>
  <testcase name="dropDown1" time="20.169" classname="com.testng.Priority"/>
  <testcase name="HandleBootstrapDropDown1" time="21.850" classname="com.testng.Priority"/>
  <testcase name="dropDown2" time="38.580" classname="com.testng.Priority">
    <failure type="java.lang.AssertionError" message="expected [Peru (+91)] but found [Peru (+51)]">
      <![CDATA[java.lang.AssertionError: expected [Peru (+91)] but found [Peru (+51)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.Priority.dropDown2(Priority.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dropDown2 -->
</testsuite> <!-- com.testng.Priority -->
